name = "Fwogkit"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ae7ccc8a6fb5f824dc32cfa6a19606455112dcfdd86c8d510273caa7bacbb96"

[versions]
fabric = "0.8.5+build.199"
minecraft = "1.15.2"
yarn = "1.15.2+build.17"
