name = "Fwogkit"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e7bda490f8d68de0add8f44a8fab371bb9548d5608e4263aa23b3aaf81ba776"

[versions]
fabric = "0.8.5+build.199"
minecraft = "1.15.2"
yarn = "1.15.2+build.17"
