name = "Adorn"
filename = "Adorn-1.8.4+1.15.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2923/662/Adorn-1.8.4+1.15.2.jar"
hash-format = "murmur2"
hash = "3123219893"

[update]
[update.curseforge]
file-id = 2923662
project-id = 320215
release-channel = "beta"
