name = "Azuma"
filename = "azuma-1.2.6-beta_1.15.2 (1).jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2926/612/azuma-1.2.6-beta_1.15.2 (1).jar"
hash-format = "murmur2"
hash = "1695476893"

[update]
[update.curseforge]
file-id = 2926612
project-id = 373883
release-channel = "beta"
