name = "Beenfo"
filename = "beenfo-1.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2875/664/beenfo-1.0.3.jar"
hash-format = "murmur2"
hash = "2045415007"

[update]
[update.curseforge]
file-id = 2875664
project-id = 357256
release-channel = "beta"
