name = "Beenfo"
filename = "beenfo-1.16-fabric0.13.1-1.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2986/659/beenfo-1.16-fabric0.13.1-1.0.3.jar"
hash-format = "murmur2"
hash = "2159003531"

[update]
[update.curseforge]
file-id = 2986659
project-id = 357256
release-channel = "beta"
