name = "Big Buckets: Fabric Edition"
filename = "bigbuckets-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2876/180/bigbuckets-1.1.0.jar"
hash-format = "murmur2"
hash = "1259042029"

[update]
[update.curseforge]
file-id = 2876180
project-id = 352959
release-channel = "beta"
