name = "Blockus"
filename = "blockus-1.5.3.3-1.15.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2988/625/blockus-1.5.3.3-1.15.2.jar"
hash-format = "murmur2"
hash = "1543367143"

[update]
[update.curseforge]
file-id = 2988625
project-id = 312289
release-channel = "beta"
