name = "Blockus"
filename = "blockus-1.5.3-1.15.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2980/45/blockus-1.5.3-1.15.2.jar"
hash-format = "murmur2"
hash = "3021637903"

[update]
[update.curseforge]
file-id = 2980045
project-id = 312289
release-channel = "beta"
