name = "Blockus"
filename = "blockus-1.6.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2991/206/blockus-1.6.0.jar"
hash-format = "murmur2"
hash = "390018949"

[update]
[update.curseforge]
file-id = 2991206
project-id = 312289
release-channel = "beta"
