name = "Blockus"
filename = "blockus-1.5.2.1-1.15.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2954/250/blockus-1.5.2.1-1.15.2.jar"
hash-format = "murmur2"
hash = "438702958"

[update]
[update.curseforge]
file-id = 2954250
project-id = 312289
release-channel = "beta"
