name = "Carpet"
filename = "fabric-carpet-1.16-1.4.0+v200623.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2986/869/fabric-carpet-1.16-1.4.0+v200623.jar"
hash-format = "murmur2"
hash = "1890220969"

[update]
[update.curseforge]
file-id = 2986869
project-id = 349239
release-channel = "beta"
