name = "Carpet"
filename = "fabric-carpet-1.15.2-1.4.0+v200623.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2986/868/fabric-carpet-1.15.2-1.4.0+v200623.jar"
hash-format = "murmur2"
hash = "4221387635"

[update]
[update.curseforge]
file-id = 2986868
project-id = 349239
release-channel = "beta"
