name = "Carpet"
filename = "fabric-carpet-1.15.2-1.3.23+v200513.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2960/461/fabric-carpet-1.15.2-1.3.23+v200513.jar"
hash-format = "murmur2"
hash = "2036002982"

[update]
[update.curseforge]
file-id = 2960461
project-id = 349239
release-channel = "beta"
