name = "Carpet"
filename = "fabric-carpet-1.15.2-1.3.26+v200604.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2972/988/fabric-carpet-1.15.2-1.3.26+v200604.jar"
hash-format = "murmur2"
hash = "3987990590"

[update]
[update.curseforge]
file-id = 2972988
project-id = 349239
release-channel = "beta"
