name = "Carpet Extra"
filename = "carpet-extra-1.16-1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2986/669/carpet-extra-1.16-1.4.0.jar"
hash-format = "murmur2"
hash = "3252928613"

[update]
[update.curseforge]
file-id = 2986669
project-id = 349240
release-channel = "beta"
