name = "CartLoaders"
filename = "cartloaders-0.0.1+1.15.2-0.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2947/696/cartloaders-0.0.1+1.15.2-0.0.1.jar"
hash-format = "murmur2"
hash = "2332144913"

[update]
[update.curseforge]
file-id = 2947696
project-id = 380831
release-channel = "beta"
