name = "Cave Biomes"
filename = "cavebiomes-0.2.2-1.15.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2966/279/cavebiomes-0.2.2-1.15.2.jar"
hash-format = "murmur2"
hash = "3659347142"

[update]
[update.curseforge]
file-id = 2966279
project-id = 371307
release-channel = "beta"
