name = "ChatCalc (Fabric and Forge)"
filename = "ChatCalc 2.1 - MC 1.15.2 - Fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2932/141/ChatCalc 2.1 - MC 1.15.2 - Fabric.jar"
hash-format = "murmur2"
hash = "76692684"

[update]
[update.curseforge]
file-id = 2932141
project-id = 374453
release-channel = "beta"
