name = "[Fabric] Expanded Storage"
filename = "expandedstorage-5.1.2+1.15.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2983/274/expandedstorage-5.1.2+1.15.2.jar"
hash-format = "murmur2"
hash = "1713922063"

[update]
[update.curseforge]
file-id = 2983274
project-id = 317856
release-channel = "beta"
