name = "Fabric API"
filename = "fabric-api-0.14.0+build.371-1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2988/824/fabric-api-0.14.0+build.371-1.16.jar"
hash-format = "murmur2"
hash = "1076012824"

[update]
[update.curseforge]
file-id = 2988824
project-id = 306612
release-channel = "beta"
