name = "Fabric API"
filename = "fabric-api-0.14.0+build.317-1.15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2988/820/fabric-api-0.14.0+build.317-1.15.jar"
hash-format = "murmur2"
hash = "788018544"

[update]
[update.curseforge]
file-id = 2988820
project-id = 306612
release-channel = "beta"
