name = "Fabric API"
filename = "fabric-api-0.12.0+build.313-1.15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2978/446/fabric-api-0.12.0+build.313-1.15.jar"
hash-format = "murmur2"
hash = "817926074"

[update]
[update.curseforge]
file-id = 2978446
project-id = 306612
release-channel = "beta"
