name = "Flax Mod (Fabric)"
filename = "Flax-1.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2842/686/Flax-1.1.1.jar"
hash-format = "murmur2"
hash = "223839573"

[update]
[update.curseforge]
file-id = 2842686
project-id = 347451
release-channel = "beta"
