name = "Flora Doubling (Forge & Fabric)"
filename = "flora-doubling-1.15.2-1.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2987/768/flora-doubling-1.15.2-1.1.1.jar"
hash-format = "murmur2"
hash = "4045558197"

[update]
[update.curseforge]
file-id = 2987768
project-id = 332831
release-channel = "beta"
