name = "Flora Doubling (Forge & Fabric)"
filename = "flora-doubling-1.16.1-1.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2987/766/flora-doubling-1.16.1-1.1.1.jar"
hash-format = "murmur2"
hash = "2850601217"

[update]
[update.curseforge]
file-id = 2987766
project-id = 332831
release-channel = "beta"
