name = "Go Down !"
filename = "godown-0.2.0+1.15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2882/107/godown-0.2.0+1.15.jar"
hash-format = "murmur2"
hash = "2283706013"

[update]
[update.curseforge]
file-id = 2882107
project-id = 360899
release-channel = "beta"
