name = "Greenstone Circuits"
filename = "greenstone-circuits-0.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2954/811/greenstone-circuits-0.0.2.jar"
hash-format = "murmur2"
hash = "3801505046"

[update]
[update.curseforge]
file-id = 2954811
project-id = 381925
release-channel = "beta"
