name = "Hwyla"
filename = "Hwyla-fabric-1.16.1-1.9.22-75.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2989/943/Hwyla-fabric-1.16.1-1.9.22-75.jar"
hash-format = "murmur2"
hash = "683652870"

[update]
[update.curseforge]
file-id = 2989943
project-id = 253449
release-channel = "beta"
