name = "I Need Keybinds"
filename = "i-need-keybinds-0.2.1-unstable.201912010804.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2835/181/i-need-keybinds-0.2.1-unstable.201912010804.jar"
hash-format = "murmur2"
hash = "404987785"

[update]
[update.curseforge]
file-id = 2835181
project-id = 331734
release-channel = "beta"
