name = "Inventory Sorter"
filename = "inventorysorter-1.15.2-17.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2869/197/inventorysorter-1.15.2-17.0.0.jar"
hash-format = "murmur2"
hash = "3817266820"

[update]
[update.curseforge]
file-id = 2869197
project-id = 240633
release-channel = "beta"
