name = "JumpOverFences"
filename = "jumpoverfences-1.15-0.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2836/560/jumpoverfences-1.15-0.0.1.jar"
hash-format = "murmur2"
hash = "4212555829"

[update]
[update.curseforge]
file-id = 2836560
project-id = 353641
release-channel = "beta"
