name = "LibGamerule"
filename = "libgamerule-0.0.4-1.15.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2888/321/libgamerule-0.0.4-1.15.2.jar"
hash-format = "murmur2"
hash = "3031564551"

[update]
[update.curseforge]
file-id = 2888321
project-id = 363435
release-channel = "beta"
