name = "Light Overlay (Rift/Forge/Fabric)"
filename = "light-overlay-4.7.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2985/650/light-overlay-4.7.0.jar"
hash-format = "murmur2"
hash = "1498966431"

[update]
[update.curseforge]
file-id = 2985650
project-id = 325492
release-channel = "beta"
