name = "Light Overlay (Rift/Forge/Fabric)"
filename = "light-overlay-5.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2990/59/light-overlay-5.4.0.jar"
hash-format = "murmur2"
hash = "1906580414"

[update]
[update.curseforge]
file-id = 2990059
project-id = 325492
release-channel = "beta"
