name = "Mod Menu"
filename = "modmenu-1.12.2+build.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2988/292/modmenu-1.12.2+build.17.jar"
hash-format = "murmur2"
hash = "832748883"

[update]
[update.curseforge]
file-id = 2988292
project-id = 308702
release-channel = "beta"
