name = "More Berries"
filename = "moreberries-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2990/110/moreberries-1.3.0.jar"
hash-format = "murmur2"
hash = "1513723011"

[update]
[update.curseforge]
file-id = 2990110
project-id = 315749
release-channel = "beta"
