name = "Not Enough Crashes"
filename = "notenoughcrashes-1.2.4+1.15.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2937/754/notenoughcrashes-1.2.4+1.15.1.jar"
hash-format = "murmur2"
hash = "2410694627"

[update]
[update.curseforge]
file-id = 2937754
project-id = 353890
release-channel = "beta"
