name = "Obsidian Pressure Plate [FABRIC]"
filename = "obsidian-pressure-plate-justfatlard-0.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2935/310/obsidian-pressure-plate-justfatlard-0.2.1.jar"
hash-format = "murmur2"
hash = "2028144717"

[update]
[update.curseforge]
file-id = 2935310
project-id = 355155
release-channel = "beta"
