name = "Ok Zoomer"
filename = "okzoomer-2.1.0-beta.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2874/706/okzoomer-2.1.0-beta.4.jar"
hash-format = "murmur2"
hash = "3531409480"

[update]
[update.curseforge]
file-id = 2874706
project-id = 354047
release-channel = "beta"
