name = "Orderly (Fabric)"
filename = "orderly-2.0.0-alpha+build.7-1.15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2875/530/orderly-2.0.0-alpha+build.7-1.15.jar"
hash-format = "murmur2"
hash = "1343092377"

[update]
[update.curseforge]
file-id = 2875530
project-id = 332547
release-channel = "beta"
