name = "Reborn Core"
filename = "RebornCore-1.16-4.3.1+build.35.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2987/629/RebornCore-1.16-4.3.1+build.35.jar"
hash-format = "murmur2"
hash = "1010096239"

[update]
[update.curseforge]
file-id = 2987629
project-id = 237903
release-channel = "beta"
