name = "Roughly Enough Items (REI)"
filename = "RoughlyEnoughItems-3.6.21.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2979/221/RoughlyEnoughItems-3.6.21.jar"
hash-format = "murmur2"
hash = "1289012957"

[update]
[update.curseforge]
file-id = 2979221
project-id = 310111
release-channel = "beta"
