name = "Roughly Enough Items Fabric (REI)"
filename = "RoughlyEnoughItems-4.5.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2988/210/RoughlyEnoughItems-4.5.5.jar"
hash-format = "murmur2"
hash = "242225872"

[update]
[update.curseforge]
file-id = 2988210
project-id = 310111
release-channel = "beta"
