name = "Secret Rooms Fabric"
filename = "secretrooms-0.9.0+1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2986/842/secretrooms-0.9.0+1.16.jar"
hash-format = "murmur2"
hash = "3704701368"

[update]
[update.curseforge]
file-id = 2986842
project-id = 359248
release-channel = "beta"
