name = "Simplex Terrain Generation"
filename = "simplexterrain-0.5.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2884/911/simplexterrain-0.5.1.jar"
hash-format = "murmur2"
hash = "1768246452"

[update]
[update.curseforge]
file-id = 2884911
project-id = 352997
release-channel = "beta"
