name = "Simplex Terrain Generation"
filename = "simplexterrain-0.6.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2989/381/simplexterrain-0.6.4.jar"
hash-format = "murmur2"
hash = "2982865115"

[update]
[update.curseforge]
file-id = 2989381
project-id = 352997
release-channel = "beta"
