name = "Terrestria"
filename = "terrestria-2.0.1+build.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2991/47/terrestria-2.0.1+build.17.jar"
hash-format = "murmur2"
hash = "634456521"

[update]
[update.curseforge]
file-id = 2991047
project-id = 323974
release-channel = "beta"
