name = "Traverse"
filename = "traverse-2.2.11+build.23.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2990/984/traverse-2.2.11+build.23.jar"
hash-format = "murmur2"
hash = "978166751"

[update]
[update.curseforge]
file-id = 2990984
project-id = 308777
release-channel = "beta"
