name = "Trees Do Not Float"
filename = "tdnf-mc116-1.10.90.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2989/91/tdnf-mc116-1.10.90.jar"
hash-format = "murmur2"
hash = "828971769"

[update]
[update.curseforge]
file-id = 2989091
project-id = 323354
release-channel = "beta"
