name = "Trinkets (Fabric)"
filename = "trinkets-2.4.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2923/16/trinkets-2.4.2.jar"
hash-format = "murmur2"
hash = "605385711"

[update]
[update.curseforge]
file-id = 2923016
project-id = 341284
release-channel = "beta"
