name = "Trinkets (Fabric)"
filename = "trinkets-2.6.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2989/877/trinkets-2.6.2.jar"
hash-format = "murmur2"
hash = "1633489112"

[update]
[update.curseforge]
file-id = 2989877
project-id = 341284
release-channel = "beta"
