name = "VoxelMap"
filename = "forgemod_VoxelMap-1.9.21_for_1.15.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2987/240/forgemod_VoxelMap-1.9.21_for_1.15.2.jar"
hash-format = "murmur2"
hash = "4091259711"

[update]
[update.curseforge]
file-id = 2987240
project-id = 225179
release-channel = "beta"
