name = "VoxelMap"
filename = "fabricmod_VoxelMap-1.9.19_for_1.15.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2970/139/fabricmod_VoxelMap-1.9.19_for_1.15.2.jar"
hash-format = "murmur2"
hash = "3434455593"

[update]
[update.curseforge]
file-id = 2970139
project-id = 225179
release-channel = "beta"
